"""empty message

Revision ID: 30672666cbc3
Revises: f858ffb33be
Create Date: 2014-08-13 01:45:53.683000

"""

# revision identifiers, used by Alembic.
revision = '30672666cbc3'
down_revision = 'f858ffb33be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like')
    ### end Alembic commands ###
