"""empty message

Revision ID: 34d66d4f00fc
Revises: 1398dd82c880
Create Date: 2014-08-06 19:43:26.955000

"""

# revision identifiers, used by Alembic.
revision = '34d66d4f00fc'
down_revision = '1398dd82c880'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
