"""empty message

Revision ID: 456c3e737525
Revises: 34d66d4f00fc
Create Date: 2014-08-06 19:55:20.071000

"""

# revision identifiers, used by Alembic.
revision = '456c3e737525'
down_revision = '34d66d4f00fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
