"""empty message

Revision ID: 1398dd82c880
Revises: None
Create Date: 2014-08-06 18:51:03.519000

"""

# revision identifiers, used by Alembic.
revision = '1398dd82c880'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
