"""empty message

Revision ID: f858ffb33be
Revises: 18ff9831476e
Create Date: 2014-08-08 20:01:13.610000

"""

# revision identifiers, used by Alembic.
revision = 'f858ffb33be'
down_revision = '18ff9831476e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'article', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'article', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('comment')
    ### end Alembic commands ###
